name: depth-net
channels:
  - pytorch
dependencies:
  - python=3.6
  - pytorch
  - torchvision
#  - cudatoolkit=10.0
  - numpy
  - scipy
  - scikit-image
  - jupyter
  - pip:
    - sacred
    - opencv-python
    - tensorflow
    - tensorboardX
